#######################################################
# 
# Node.py
# Python implementation of the Class Node
# Generated by Enterprise Architect
# Created on:      01-juil.-2013 20:46:12
# Original author: Romain
# 
#######################################################
from Var import *

class Node:

	def __init__(self, type, shaderType):
		self.type = type
		self.name = 'None'
		self.linkList = []
		self.linkManager = None
		self.shaderType = shaderType
		self.inVars = {}
		self.outVars = {}

	def getName(self) :
		return self.name
		
	def setName(self, name) :
		self.name = name
		
	def getType(self) :
		return self.type
		
	def getShaderType(self) :
		return self.shaderType
	
	def setLinkManager(self, linkManager) :
		self.linkManager = linkManager
	
	def getLinkList(self) :
		return self.linkList
	
	def setLinkList(self, value) :
		self.linkList = value
	
	## @fn getInVar(name)
	# @brief Retrieve an input variable of the node using its name
	# @param name A string giving the name of the variable
	# @return A reference on the corresponding variable
	def getInVar(self, name) :
		return self.inVars[name]
		
	## @fn getOutVar(name)
	# @brief Retrieve an output variable of the node using its name
	# @param name A string giving the name of the variable
	# @return A reference on the corresponding variable
	def getOutVar(self, name) :
		return self.outVars[name]
	
	def getInVarList(self) :
		return self.inVars
		
	def getOutVarList(self) :
		return self.outVars	
		