#######################################################
#
# ShaderType.py
# Python implementation of the Class ShaderType
# Generated by Enterprise Architect
# Created on:      11-dec.-2013 20:46:13
# Original author: Romain
#
#######################################################
PIXEL_SHADER = 1
VERTEX_SHADER = 0
