#######################################################
#
# Shader.py
# Python implementation of the Class Shader
# Generated by Enterprise Architect
# Created on:      01-juil.-2013 20:46:13
# Original author: Romain
#
#######################################################
from Node import *

class Shader(Node):

	def __init__(self, shaderType):
		Node.__init__(self, 1, shaderType)
		self.shaderType = shaderType

	def getParams(self) :
		return (self.inVars, self.outVars)

	def printName(self) :
		print self.name